version: '3.8'

services:
  player0:
    image: mp-spdz
    build:
      context: .
      dockerfile: Dockerfile
      args:
        program: mal-shamir-offline.x
    working_dir: /usr/src/MP-SPDZ
    volumes:
      - ./Compiler:/usr/src/MP-SPDZ/Compiler
      - ./CONFIG:/usr/src/MP-SPDZ/CONFIG
      - ./Makefile:/usr/src/MP-SPDZ/Makefile
      - ./Programs/Source:/usr/src/MP-SPDZ/Programs/Source
      - ./Scripts:/usr/src/MP-SPDZ/Scripts
    command: mal-shamir-offline.x -v -N 4 -T 1 -p 0 --prime ${PRIME} --prep-dir ${PREP_DIR} -h player0 tutorial

  player1:
    image: mp-spdz
    build:
      context: .
      dockerfile: Dockerfile
      args:
        program: mal-shamir-offline.x
    working_dir: /usr/src/MP-SPDZ
    volumes:
      - ./Compiler:/usr/src/MP-SPDZ/Compiler
      - ./CONFIG:/usr/src/MP-SPDZ/CONFIG
      - ./Makefile:/usr/src/MP-SPDZ/Makefile
      - ./Programs/Source:/usr/src/MP-SPDZ/Programs/Source
      - ./Scripts:/usr/src/MP-SPDZ/Scripts
    command: mal-shamir-offline.x -v -N 4 -T 1 -p 1 --prime ${PRIME} --prep-dir ${PREP_DIR} -h player0 tutorial

  player2:
    image: mp-spdz
    build:
      context: .
      dockerfile: Dockerfile
      args:
        program: mal-shamir-offline.x
    working_dir: /usr/src/MP-SPDZ
    volumes:
      - ./Compiler:/usr/src/MP-SPDZ/Compiler
      - ./CONFIG:/usr/src/MP-SPDZ/CONFIG
      - ./Makefile:/usr/src/MP-SPDZ/Makefile
      - ./Programs/Source:/usr/src/MP-SPDZ/Programs/Source
      - ./Scripts:/usr/src/MP-SPDZ/Scripts
    command: mal-shamir-offline.x -v -N 4 -T 1 -p 2 --prime ${PRIME} --prep-dir ${PREP_DIR} -h player0 tutorial

  player3:
    image: mp-spdz
    build:
      context: .
      dockerfile: Dockerfile
      args:
        program: mal-shamir-offline.x
    working_dir: /usr/src/MP-SPDZ
    volumes:
      - ./Compiler:/usr/src/MP-SPDZ/Compiler
      - ./CONFIG:/usr/src/MP-SPDZ/CONFIG
      - ./Makefile:/usr/src/MP-SPDZ/Makefile
      - ./Programs/Source:/usr/src/MP-SPDZ/Programs/Source
      - ./Scripts:/usr/src/MP-SPDZ/Scripts
    command: mal-shamir-offline.x -v -N 4 -T 1 -p 3 --prime ${PRIME} --prep-dir ${PREP_DIR} -h player0 tutorial
