version: "3.9"

services:
  node0:
    image: mp-spdz
    build:
      context: .
      dockerfile: Dockerfile
      args:
        machine: malicious-shamir-party.x
        prep_dir: /opt/preprocessing-data
        ssl_dir: /opt/ssl
        cryptoplayers: 3
        gfp_mod_sz: 4
        compile_options: "-v -C --field=256"
        src: average
    environment:
      PREP_DIR: ${PREP_DIR}
      PRIME: ${PRIME}
      LEADER: ${LEADER}
    working_dir: /usr/src/MP-SPDZ
    volumes:
      - ./Compiler:/usr/src/MP-SPDZ/Compiler
      - ./CONFIG:/usr/src/MP-SPDZ/CONFIG
      - ./Makefile:/usr/src/MP-SPDZ/Makefile
      - ./Programs/Source:/usr/src/MP-SPDZ/Programs/Source
      - ./Scripts:/usr/src/MP-SPDZ/Scripts
      - ./network.config:/usr/src/MP-SPDZ/network.config
    #command: malicious-shamir-party.x --prime $PRIME --hostname ${LEADER} --nparties 3 --threshold 1 --player 0 average
    command: malicious-shamir-party.x --prime $PRIME --ip-file-name network.config --nparties 3 --threshold 1 --player 0 average
  node1:
    image: mp-spdz
    build:
      context: .
      dockerfile: Dockerfile
      args:
        machine: malicious-shamir-party.x
        prep_dir: /opt/preprocessing-data
        ssl_dir: /opt/ssl
        cryptoplayers: 3
        gfp_mod_sz: 4
        compile_options: "-v -C --field=256"
        src: average
    environment:
      PREP_DIR: ${PREP_DIR}
      PRIME: ${PRIME}
      LEADER: ${LEADER}
    working_dir: /usr/src/MP-SPDZ
    volumes:
      - ./Compiler:/usr/src/MP-SPDZ/Compiler
      - ./CONFIG:/usr/src/MP-SPDZ/CONFIG
      - ./Makefile:/usr/src/MP-SPDZ/Makefile
      - ./Programs/Source:/usr/src/MP-SPDZ/Programs/Source
      - ./Scripts:/usr/src/MP-SPDZ/Scripts
      - ./network.config:/usr/src/MP-SPDZ/network.config
    command: malicious-shamir-party.x --prime $PRIME --ip-file-name network.config --nparties 3 --threshold 1 --player 1 average
  node2:
    image: mp-spdz
    build:
      context: .
      dockerfile: Dockerfile
      args:
        machine: malicious-shamir-party.x
        prep_dir: /opt/preprocessing-data
        ssl_dir: /opt/ssl
        cryptoplayers: 3
        gfp_mod_sz: 4
        compile_options: "-v -C --field=256"
        src: average
    environment:
      PREP_DIR: ${PREP_DIR}
      PRIME: ${PRIME}
      LEADER: ${LEADER}
    working_dir: /usr/src/MP-SPDZ
    volumes:
      - ./Compiler:/usr/src/MP-SPDZ/Compiler
      - ./CONFIG:/usr/src/MP-SPDZ/CONFIG
      - ./Makefile:/usr/src/MP-SPDZ/Makefile
      - ./Programs/Source:/usr/src/MP-SPDZ/Programs/Source
      - ./Scripts:/usr/src/MP-SPDZ/Scripts
      - ./network.config:/usr/src/MP-SPDZ/network.config
    command: malicious-shamir-party.x --prime $PRIME --ip-file-name network.config --nparties 3 --threshold 1 --player 2 average
