name: ci-build-and-push-image

on:
  push:
    branches: [ dev ]

  workflow_dispatch:

jobs:
  mpspdz-base:
    runs-on: ubuntu-20.04

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set Short SHA
        id: vars
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"
      -
        name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: mpspdz - build & push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          target: buildenv
          build-args: |
            arch=x86-64
            use_ntl=1
            prep_dir=/opt/preprocessing-data
            ssl_dir="/opt/ssl"
            cryptoplayers=4
          tags: |
            initc3/mpspdz,
            initc3/mpspdz:${{ github.ref_name }},
            initc3/mpspdz:${{ steps.vars.outputs.short_sha }}
          cache-from: type=registry,ref=initc3/mpspdz:buildcache
          cache-to: type=registry,ref=initc3/mpspdz:buildcache,mode=max

  malicious-shamir-party:
    runs-on: ubuntu-20.04

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set Short SHA
        id: vars
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"
      -
        name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: malicious-shamir-party.x - build & push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          target: machine
          build-args: |
            arch=x86-64
            machine=malicious-shamir-party.x
            prep_dir=/opt/preprocessing-data
            ssl_dir=/opt/ssl
            cryptoplayers=4
            gfp_mod_sz=4
          tags: |
            initc3/malicious-shamir-party.x,
            initc3/malicious-shamir-party.x:${{ github.ref_name }},
            initc3/malicious-shamir-party.x:${{ steps.vars.outputs.short_sha }}
          cache-from: type=registry,ref=initc3/malicious-shamir-party.x:buildcache
          cache-to: type=registry,ref=initc3/malicious-shamir-party.x:buildcache,mode=max

  mal-shamir-offline:
    runs-on: ubuntu-20.04

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set Short SHA
        id: vars
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"
      -
        name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: mal-shamir-offline.x - build & push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          target: machine
          build-args: |
            arch=x86-64
            machine=mal-shamir-offline.x
            prep_dir=/opt/preprocessing-data
            ssl_dir=/opt/ssl
            cryptoplayers=4
            gfp_mod_sz=4
          tags: |
            initc3/mal-shamir-offline.x,
            initc3/mal-shamir-offline.x:${{ github.ref_name }},
            initc3/mal-shamir-offline.x:${{ steps.vars.outputs.short_sha }}
          cache-from: type=registry,ref=initc3/mal-shamir-offline.x:buildcache
          cache-to: type=registry,ref=initc3/mal-shamir-offline.x:buildcache,mode=max

  random-shamir:
    runs-on: ubuntu-20.04

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set Short SHA
        id: vars
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"
      -
        name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: random-shamir.x - build & push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          target: machine
          build-args: |
            arch=x86-64
            machine=random-shamir.x
            prep_dir=/opt/inputmask-shares
            ssl_dir=/opt/ssl
            cryptoplayers=4
            gfp_mod_sz=4
          tags: |
            initc3/random-shamir.x,
            initc3/random-shamir.x:${{ github.ref_name }},
            initc3/random-shamir.x:${{ steps.vars.outputs.short_sha }}
          cache-from: type=registry,ref=initc3/random-shamir.x:buildcache
          cache-to: type=registry,ref=initc3/random-shamir.x:buildcache,mode=max

  mal-shamir-bmr:
    runs-on: ubuntu-20.04

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set Short SHA
        id: vars
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"
      -
        name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: mal-shamir-bmr - build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          build-args: |
            arch=x86-64
            machine=mal-shamir-bmr-party.x
            prep_dir=/opt/preprocessing-data
            ssl_dir=/opt/ssl
            cryptoplayers=3
            src=tutorial
            compile_options=--binary=32
          tags: |
            initc3/mal-shamir-bmr,
            initc3/mal-shamir-bmr:${{ github.ref_name }},
            initc3/mal-shamir-bmr:${{ steps.vars.outputs.short_sha }}
          cache-from: type=registry,ref=initc3/mal-shamir-bmr:buildcache
          cache-to: type=registry,ref=initc3/mal-shamir-bmr:buildcache,mode=max
